---
title: "CS598 - Project 3"
author: "Xiaoming Ji"
output: pdf_document
---
# Computer System

## Hardware
- Dell Precision Tower 5810
- CPU: Intel Xeon E5-1607 @ 3.10GHz
- Memory: 32GB

## Software
- OS: Windows 10 Professional 64bit
- R: 3.5.1
- R Packages:

```{r, eval=FALSE, include=FALSE}
data.all = read.csv("loan_stat542.csv")
test.id.all = read.csv("Project3_test_id.csv")

for (i in 1:(dim(test.id.all)[2])){
  
  train.data = data.all[!data.all$id %in% test.id.all[,i],]
  write.csv(train.data, file=paste("train", i, ".csv", sep=""), row.names = FALSE)
  test.data = data.all[data.all$id %in% test.id.all[,i],]
  
  label.data = test.data[,c("id", "loan_status")]
  colnames(label.data)[2] = 'y'
  label.data$y[label.data$y == "Charged Off"] = "Default"
  label.data$y = as.numeric(label.data$y)
  label.data$y[label.data$y == 3] = 0
  label.data$y[label.data$y == 2] = 1
  write.csv(label.data, file=paste("label", i, ".csv", sep=""), row.names = FALSE)
  
  test.data = test.data[, c("loan_status") != names(test.data)]
  write.csv(test.data, file=paste("test", i, ".csv", sep=""), row.names = FALSE)
}
```

```{r}
#########################################################################
# log-loss function
logLoss = function(y, p){
    if (length(p) != length(y)){
        stop('Lengths of prediction and labels do not match.')
    }
    
    if (any(p < 0)){
        stop('Negative probability provided.')
    }
    
    p = pmax(pmin(p, 1 - 10^(-15)), 10^(-15))
    mean(ifelse(y == 1, -log(p), -log(1 - p)))
}

#########################################################################
# Test code begins
TRAIN_FILE_NAME = "train1.csv"
TEST_FILE_NAME = "test1.csv"
LABEL_FILE_NAME = "label1.csv"

start.time = Sys.time()
source('mymain.R')
end.time = Sys.time()
run.time = as.numeric(difftime(end.time, start.time, units = 'min'))
```

```{r}

```

```{r}
# # submission files
# allFiles = list.files()
# subFiles = grep('mysubmission', allFiles, value = TRUE, 
#                 ignore.case = TRUE)
# 
# # calculate the test error on the test set
# test = read.csv('test.csv')
# 
# label = read.csv('label.csv', sep = ',')
# err = rep(NA, length(subFiles))
# for (met in 1:length(subFiles)){
# 
#     prediction = read.csv(subFiles[met], sep = ',')
#     yp = merge(prediction, label, by = 'id', all.y = TRUE)
#     err[met] = with(yp, logLoss(y, prob))
#     
# }
# 
# #########################################################################
# write.table(err, file = 'proj_3.csv', sep = ',', row.names = FALSE,
#             col.names = FALSE)
# write.table(run.time, file = 'proj_3.csv', sep = ',', 
#             row.names = FALSE, col.names = FALSE, append = TRUE)
```

